insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Ciclodan', 384, 261975);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Personal Care Sensitive Skin Deep Cleaning Astringent', 331, 262070);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Effexor', 449, 212944);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'MUCUS RELIEF', 445, 381393);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Xopenex', 413, 120991);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'OXYGEN', 303, 142578);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'ANBESOL REGULAR STRENGTH', 420, 24488);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Irbesartan', 384, 343883);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Enalapril Maleate', 40, 216409);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Tekturna HCT', 138, 302669);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Fluconazole', 324, 348610);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'allergy relief', 409, 11745);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Sore Throat Right Side', 122, 155099);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Neuralgia', 429, 273509);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Antiseptic', 163, 207230);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'SMITH BROS HONEY LEMON Cough Drops', 137, 374898);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Gabapentin', 310, 413167);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Risperidone', 421, 402039);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'DERMAKLEAR AKNE TREATMENT WITH SULFUR', 129, 26244);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Acne Care', 230, 52441);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'Servo-Stat TE', 205, 312647);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Atenolol', 270, 248545);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'DiorSkin Nude 020 Beige Praline', 300, 236252);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'ARTISTRY Time Defiance UV Defense SPF 50 Ultra Facial Sunscreen', 314, 265320);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'HAND SANITIZER', 132, 298623);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'phentermine hydrochloride', 254, 29906);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'NEUROSPORA INTERMEDIA', 424, 259528);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (2, 'cold relief', 69, 230064);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Levora', 42, 116808);
insert into Thuoc (ID_DonVi, TenThuoc, SoLuong, DonGia) values (1, 'Aspirin', 308, 181968);
